-- =========================================================================
-- FISH WIKI - TOPLU BALIK EKLEME SQL SORGUSU (BÖLÜM 1: A - E)
-- =========================================================================

INSERT INTO fishes (
  name_tr,
  name_en,
  scientific_name,
  water_type,
  short_info_tr,
  short_info_en,
  limit_size,
  ban_periods,
  active_seasons,
  recommended_gear,
  favorite_baits,
  primary_regions,
  taste_rating,
  cooking_tips_tr,
  cooking_tips_en,
  description_tr,
  description_en,
  image_url,
  is_active
) VALUES 
(
  'Abant Alası',
  'Abant Trout',
  'Salmo trutta abanticus',
  'Tatlı Su',
  'Sadece Türkiye''ye özgü, soğuk su seven endemik bir alabalık türü.',
  'Endemic cold-water trout species native only to Turkey.',
  'Asgari 25 cm (Günlük limit: 3 Adet)',
  '1 Ekim - 28 Şubat (Orman içi sularda)',
  'İlkbahar, Yaz',
  'Fly-fishing, LRF, Döner Kaşık (Mepps)',
  'Suni Sinek, Küçük Döner Kaşıklar, Mikro Silikonlar',
  'Abant Gölü, Yedigöller ve Bolu/Düzce yüksek rakımlı dereler',
  '5/5 Yıldız - Yüksek Yağ Oranı',
  'Tereyağında hafifçe tavada kızartılır veya kiremitte fırınlanır.',
  'Lightly pan-fried in butter or baked in a clay pot.',
  'Özellikle göl ve derelerde sinek oltası (fly-fishing) ile avlanması büyük keyif veren, koruma altındaki endemik bir tür. LRF (Light Rock Fishing) takımlarıyla mikro sahtelere harika tepki verir.',
  'An endemic, protected species that offers great sport for fly-fishing and LRF enthusiasts in high altitude lakes and streams.',
  NULL,
  TRUE
),
(
  'Akya',
  'Leerfish',
  'Lichia amia',
  'Tuzlu Su',
  'Kıyıların en güçlü ve saldırgan pelajik avcılarından biri.',
  'One of the most powerful and aggressive pelagic predators of the coasts.',
  'Asgari 50 cm',
  'Yıl boyu serbest',
  'Yaz, Sonbahar',
  'Ağır Spinning, Shore Jigging, Canlı Yem',
  'Canlı Zargana, İstavrit, Su Üstü Popper Sahteler',
  'Akdeniz ve Ege Kıyıları, Antalya, İzmir',
  '3/5 Yıldız - Sıkı ve Kuru Et',
  'Kuşbaşı doğranıp şişte veya fırında bol zeytinyağı ile pişirilmesi önerilir.',
  'Best cubed and grilled on skewers or baked with plenty of olive oil.',
  'Kıyıdan ve tekneden büyük sahteler veya canlı yemlerle avlanan, inanılmaz mücadeleci bir trofe balığıdır. Oltaya bindiğinde yorucu bir direnç gösterir.',
  'A massive trophy fish targeted with large lures or live bait, known for its incredible fighting spirit.',
  NULL,
  TRUE
),
(
  'Alabalık (Gökkuşağı)',
  'Rainbow Trout',
  'Oncorhynchus mykiss',
  'Tatlı Su',
  'Akarsu ve göllerin hızlı, çevik ve obur balığı.',
  'Fast, agile, and voracious fish of streams and lakes.',
  'Limit Yok (İstilacı/Üretim türü olarak kabul edilir)',
  'Doğal popülasyonlar için 1 Ekim - 28 Şubat',
  'İlkbahar, Sonbahar',
  'Fly-fishing, LRF (1-5g), Mepps Kaşık',
  'Suni Sinek (Nymph, Dry Fly), Mepps 1-2 No, Alabalık Hamuru',
  'Soğuk ve akıntılı dereler, baraj gölleri',
  '4/5 Yıldız - Lezzetli ve Kılçıksız',
  'Mısır ununa bulanıp tavada kızartılır veya fırında tereyağlı yapılır.',
  'Coated in cornmeal and pan-fried or baked with butter.',
  'Hızlı akan sularda ultra hafif LRF takımları ve döner kaşıklarla avlanması muhteşem bir aksiyon sunar. Akıntıya karşı yüzmeyi sever.',
  'Provides excellent action in fast-flowing streams when targeted with ultralight gear and spinners.',
  NULL,
  TRUE
),
(
  'Aynalı Sazan',
  'Mirror Carp',
  'Cyprinus carpio',
  'Tatlı Su',
  'Tatlı suların en popüler, iri pullu ve mücadeleci dip balığı.',
  'The most popular and combative bottom-dwelling fish of freshwaters.',
  'Asgari 40 cm',
  'İç sularda 15 Mart - 15 Haziran (Bölgelere göre değişir)',
  'İlkbahar, Yaz, Sonbahar',
  'Sazan Montajı (Hair Rig), Ağır Dip Takımı',
  'Boilie, Haşlanmış Mısır, Kaplan Fıstığı (Tiger Nut)',
  'Anadolu''daki hemen tüm gölet ve barajlar',
  '3/5 Yıldız - Kılçıklı fakat Lezzetli',
  'Çizikler atılarak fırında kızartılır veya güveçte sebzeli buğulaması yapılır.',
  'Scored and baked in the oven, or stewed with vegetables.',
  'Özel sazan takımları, alarmlı sehpalar (rod pod) ve yüksek çekerli misinalarla günlerce süren kamp avcılığının bir numaralı hedefidir.',
  'The number one target for multi-day camping trips using specialized carp gear and bite alarms.',
  NULL,
  TRUE
),
(
  'Barbunya',
  'Red Mullet',
  'Mullus barbatus',
  'Tuzlu Su',
  'Pembe/kırmızı rengi ve çene altı bıyıklarıyla bilinen dip balığı.',
  'Pink/red bottom-dwelling fish known for its chin barbels.',
  'Asgari 13 cm',
  '15 Nisan - 31 Ağustos (Trol yasağı dönemi)',
  'Yaz, Sonbahar',
  'Yemli İnce Dip Takımı',
  'Karides, Sülünes, Boru Kurdu',
  'Ege, Marmara ve Akdeniz kıyıları',
  '5/5 Yıldız - Tavaların Prensi',
  'Mısır unu ile tavada bütün olarak nar gibi kızartılır.',
  'Fried whole in a pan with corn flour until crispy.',
  'Kumluk diplerde sürüler halinde dolaşır. Çok hassas vuruşları olduğu için ince uçlu hassas kamışlarla avlanmalıdır.',
  'Travels in schools over sandy bottoms. Should be targeted with sensitive tip rods due to subtle bites.',
  NULL,
  TRUE
),
(
  'Bıyıklı Balık',
  'Barbel',
  'Barbus barbus',
  'Tatlı Su',
  'Akarsuların dip akıntılarında yaşayan, güçlü bir nehir türü.',
  'A strong river species living in fast bottom currents.',
  'Asgari 20 cm',
  '15 Mart - 15 Haziran (Bölgeye göre)',
  'İlkbahar, Yaz',
  'LRF, Dip Takımı, Feeder',
  'Solucan, Tavuk Ciğeri, Kaşar Peyniri',
  'Melen Çayı, Kızılırmak, Sakarya Nehri ve taşlık dereler',
  '2/5 Yıldız - Çok Kılçıklı',
  'Kılçık sorunu nedeniyle genellikle fileto çıkarılıp kıyma yapılarak köftesi tüketilir.',
  'Due to many bones, often filleted and minced to make fish cakes.',
  'Özellikle nehirlerin taşlık ve akıntılı bölgelerinde yaşar. LRF takımlarına bindiğinde akıntıyı da arkasına alarak inanılmaz bir mücadele sergiler.',
  'A very strong fish targeted in rocky and fast-flowing river sections. Offers an intense fight on light gear.',
  NULL,
  TRUE
),
(
  'Çapak Balığı',
  'Common Bream',
  'Abramis brama',
  'Tatlı Su',
  'Yassı ve yüksek gövdeli, sürüler halinde gezen göl balığı.',
  'Deep-bodied, schooling lake fish that feeds on the bottom.',
  'Asgari 20 cm',
  '15 Mart - 15 Haziran',
  'İlkbahar, Yaz',
  'Şamandıralı Takım, Feeder (Yemlikli) Dip Oltası',
  'Tatlı Mısır, Kurtçuk (Maggot), Solucan',
  'Marmara ve İç Anadolu''daki büyük göller ve yavaş akan nehirler',
  '2/5 Yıldız - İnce Kılçıklı',
  'Tüketimi çok popüler değildir, genelde sportif amaçlı avlanır veya çizik atılarak kızartılır.',
  'Not commonly consumed, mostly targeted for sport.',
  'Yemlemeye (mazmuz) çok hızlı tepki verir. Hassas şamandıra takımları ile durgun sularda sportif avcılığı oldukça keyiflidir.',
  'Responds very well to groundbait. Sport fishing with sensitive floats is very popular in still waters.',
  NULL,
  TRUE
),
(
  'Çizgili Mercan (Mırmır)',
  'Striped Seabream',
  'Lithognathus mormyrus',
  'Tuzlu Su',
  'Kumluk sahillerin gümüş renkli, dikey çizgili efendisi.',
  'Silver-colored, vertically striped master of sandy beaches.',
  'Asgari 15 cm',
  'Yıl boyu serbest',
  'Yaz, Sonbahar',
  'Surfcasting, İnce Dip Takımı, LRF',
  'Boru Kurdu, Sülünes, Yengeç',
  'Ege ve Akdeniz kumsalları, Marmara Denizi',
  '4/5 Yıldız - Beyaz ve Sıkı Et',
  'Izgarada veya fırında az yağlı pişirmeye çok uygundur.',
  'Highly suitable for grilling or baking.',
  'Özellikle gece avlarında surfcasting disiplini ile kumsallardan uzağa atılarak avlanır. Kumu eşeleyerek beslendiği için dipten gelen yemlere duyarlıdır.',
  'Targeted from sandy beaches, especially during night fishing, using the surfcasting discipline.',
  NULL,
  TRUE
),
(
  'Dil Balığı',
  'Common Sole',
  'Solea solea',
  'Tuzlu Su',
  'Kuma gömülerek yaşayan, yassı formlu usta kamuflajcı.',
  'Flat bottom-dwelling fish that lives buried in sand, mastering camouflage.',
  'Asgari 20 cm',
  '1 Ocak - 1 Şubat (Bölgesel kısıtlamalar uygulanabilir)',
  'Kış, İlkbahar',
  'Çok İnce Dip Takımı (Hırsızlı)',
  'Küçük Karides, Sülünes, Boru Kurdu',
  'Ege ve Akdeniz kumluk sığlıkları',
  '5/5 Yıldız - Kılçıksız, Lokum Gibi',
  'Kılçıksız olduğu için tereyağlı tavada Sole Meunière usulü yapılır.',
  'Cooked Sole Meunière style in butter due to being boneless.',
  'Ağzı çok küçük olduğu için oldukça küçük iğneler (ör: 8-10 numara) kullanılmalıdır. Gündüz kuma gömülür, gece avlanmaya çıkar.',
  'Requires very small hooks due to a tiny mouth. Buries in sand during the day and hunts at night.',
  NULL,
  TRUE
),
(
  'Eşkina',
  'Brown Meagre',
  'Sciaena umbra',
  'Tuzlu Su',
  'Kayalık boşluklarında saklanan, gözleri karanlığa alışkın gece avcısı.',
  'Nocturnal hunter hiding in rocky crevices, adapted to darkness.',
  'Asgari 30 cm (Tavsiye edilen sportif limit)',
  'Yıl boyu serbest (Ancak sayılarının azalması nedeniyle limitlere dikkat edilmeli)',
  'İlkbahar, Yaz, Sonbahar',
  'LRF (Jighead & Silikon), Şamandıralı Kayalık Takımı',
  'Canlı Teke (Karides), Yengeç, Boru Kurdu, Fosforlu Silikonlar',
  'Marmara, Karadeniz ve Ege kayalık mendirekleri',
  '4/5 Yıldız - Lezzetli Beyaz Et',
  'Fırında patates ve sebzelerle veya buğulama olarak mükemmeldir.',
  'Excellent baked with vegetables or stewed.',
  'LRF tutkunlarının kayalık mendireklerde gece avlamayı en çok sevdiği trofe balıklardan biridir. Oltaya takıldığında kayaların altına kaçma eğilimi gösterir.',
  'One of the favorite trophy fishes for LRF enthusiasts targeting rocky breakwaters at night.',
  NULL,
  TRUE
);

-- =========================================================================
-- FISH WIKI - TOPLU BALIK EKLEME SQL SORGUSU (BÖLÜM 2: F - M)
-- =========================================================================

INSERT INTO fishes (
  name_tr,
  name_en,
  scientific_name,
  water_type,
  short_info_tr,
  short_info_en,
  limit_size,
  ban_periods,
  active_seasons,
  recommended_gear,
  favorite_baits,
  primary_regions,
  taste_rating,
  cooking_tips_tr,
  cooking_tips_en,
  description_tr,
  description_en,
  image_url,
  is_active
) VALUES 
(
  'Fener Balığı',
  'Anglerfish',
  'Lophius piscatorius',
  'Tuzlu Su',
  'Kafasındaki doğal oltasıyla avlanan, derin suların kamuflaj ustası.',
  'Deep-water camouflage master that hunts using a natural lure on its head.',
  'Asgari 50 cm',
  'Yıl boyu serbest',
  'Kış, İlkbahar',
  'Derin Su Dip Takımı, Parakete',
  'Bütün Sübye, Kalamar, İzmarit',
  'Ege ve Akdeniz derinlikleri, Marmara',
  '5/5 Yıldız - Efsanevi Lezzet',
  'Kafası çorbada kullanılır, gövdesi fileto çıkarılıp tavada veya kavurma olarak pişirilir.',
  'Head is used for soup, while the tail is filleted and pan-fried.',
  'Görüntüsü ürkütücü olsa da denizlerin en lezzetli etine sahip balıklarındandır. Çok derin sularda yaşadığı için sportif avcılığı nadirdir.',
  'Despite its scary appearance, it has one of the most delicious meats. Rarely caught sport fishing due to its deep habitat.',
  NULL,
  TRUE
),
(
  'Gümüş Balığı',
  'Sand Smelt',
  'Atherina boyeri',
  'Tatlı Su',
  'Sürüler halinde gezen, yarı saydam ufak yapılı bir tür.',
  'Small, semi-transparent schooling fish.',
  'Limit Yok (Sportif olarak yasal boy sınırı belirtilmemiştir)',
  '15 Mart - 15 Haziran (İç sularda)',
  'İlkbahar, Yaz',
  'İnce Çapari, Şamandıralı Hassas Takım',
  'Hamur, Küçük Kurtçuklar',
  'Sapanca, İznik gibi büyük göller ve barajlar',
  '4/5 Yıldız - Çerezlik',
  'Mısır ununa bulanıp bütün olarak yağda kızartılır, cips gibi yenir.',
  'Coated in cornmeal and deep-fried whole, eaten like chips.',
  'Özellikle göllerde büyük sürüler oluşturur. İnce uçlu takımlarla tutması eğlencelidir, ayrıca iri avcı balıklar (Turna, Sudak) için mükemmel bir canlı yemdir.',
  'Forms large schools in lakes. Fun to catch with light gear and serves as excellent live bait for larger predators.',
  NULL,
  TRUE
),
(
  'Hamsi',
  'European Anchovy',
  'Engraulis encrasicolus',
  'Tuzlu Su',
  'Karadeniz''in gümüş renkli, sürü halinde göç eden efsanesi.',
  'The silver-colored, migrating schooling legend of the Black Sea.',
  'Asgari 9 cm',
  '15 Nisan - 31 Ağustos (Endüstriyel avcılık yasağı)',
  'Kış',
  'Çapari',
  'Yemsiz (Tüylü Çapari)',
  'Tüm Karadeniz, Marmara Denizi',
  '5/5 Yıldız - Kültürel Miras',
  'Mısır unuyla tavada dizilerek (Hamsi Kuşu) veya ızgarada yapılır.',
  'Coated in corn flour and pan-fried in a circular pattern, or grilled.',
  'Sportif kıyı avcılığında kış aylarında Karadeniz kıyılarından ince çaparilerle alınabilir. Suyun soğumasıyla yağlanır ve lezzetlenir.',
  'Can be caught with delicate sabiki rigs from the shore during winter. Becomes fattier and tastier as water cools.',
  NULL,
  TRUE
),
(
  'İstavrit',
  'Atlantic Horse Mackerel',
  'Trachurus trachurus',
  'Tuzlu Su',
  'Kıyı balıkçılığının en popüler ve erişilebilir türü.',
  'The most popular and accessible species in coastal fishing.',
  'Asgari 13 cm',
  'Yıl boyu serbest (Bölgesel ticari yasaklar hariç)',
  'İlkbahar, Yaz, Sonbahar, Kış',
  'Çapari, LRF (1-3g Jighead)',
  'Yeşil/Beyaz Tüylü Çapari, Mikro Silikonlar, Kokulu Yemler (Isome)',
  'İstanbul Boğazı, Marmara, Karadeniz ve Ege Kıyıları',
  '4/5 Yıldız - Tavada Çıtır',
  'Tavada kızartması klasiktir, irileri (Sarıkanat) ızgara da yapılabilir.',
  'Pan-frying is a classic; larger ones can also be grilled.',
  'Özellikle LRF disiplinine giriş yapanların ilk gözdesidir. Gece ışık alan meralarda mikro silikonlarla avlamak inanılmaz keyiflidir.',
  'The perfect target for LRF beginners. Catching them at night under illuminated piers using micro soft plastics is extremely fun.',
  NULL,
  TRUE
),
(
  'Kalkan',
  'Turbot',
  'Scophthalmus maximus',
  'Tuzlu Su',
  'Karadeniz''in kumluk diplerine gizlenen, üzeri düğmeli yassı balık.',
  'Flatfish of the Black Sea with bony tubercles, hiding in sandy bottoms.',
  'Asgari 45 cm',
  '15 Nisan - 15 Haziran',
  'İlkbahar, Kış',
  'Ağır Dip Takımı (Özel Kalkan İğneli)',
  'İstavrit, Mezgit, Taze Hamsi Fileto',
  'Batı Karadeniz, İstanbul Boğazı girişleri',
  '5/5 Yıldız - Üst Düzey Lezzet',
  'Tavada kızartılır veya fırında sebzeli olarak pişirilir.',
  'Fried in a pan or baked in the oven with vegetables.',
  'Avcılığı çok sabır gerektirir. Kış ve ilkbahar aylarında kumsallardan veya dalgakıranlardan uzak atış (surfcasting) ile taze yem kullanılarak aranır.',
  'Requires great patience. Targeted via surfcasting from sandy beaches using fresh bait fish during winter and spring.',
  NULL,
  TRUE
),
(
  'Kızılkanat',
  'Rudd',
  'Scardinius erythrophthalmus',
  'Tatlı Su',
  'Kırmızı yüzgeçleriyle bilinen, sazlık önlerinde avlanan tatlı su balığı.',
  'Freshwater fish known for its red fins, often hunting near reeds.',
  'Limit Yok (Boy limiti yoktur, sportif amaçlı geri salınması önerilir)',
  '15 Mart - 15 Haziran',
  'İlkbahar, Yaz',
  'Şamandıralı Hafif Takım, LRF (Mikro Kaşık)',
  'Solucan, Hamur, Mısır, Küçük Böcekler',
  'Sazlık barındıran tüm yavaş akan nehirler ve göller',
  '2/5 Yıldız - Çok Kılçıklı',
  'Genellikle sportif amaçlı (Catch & Release) avlanır, eti tercih edilmez.',
  'Mostly targeted for sport (Catch & Release), meat is not preferred.',
  'Su yüzeyine yakın beslenir. Yaz akşamları sazlık kenarlarına atılan hafif şamandıralı takımları hızla suya gömmesiyle bilinen, çok atik bir balıktır.',
  'Feeds near the surface. Known for quickly pulling down light floats cast near reeds on summer evenings.',
  NULL,
  TRUE
),
(
  'Tatlı Su Kefali (Kasna)',
  'European Chub',
  'Squalius cephalus',
  'Tatlı Su',
  'Akarsu avcılığının gözdesi, yüzeyden beslenmeyi seven zeki avcı.',
  'The star of stream fishing, an intelligent predator that feeds off the surface.',
  'Asgari 20 cm',
  '15 Mart - 15 Haziran (İç sular)',
  'İlkbahar, Yaz, Sonbahar',
  'LRF (0.5-5g), Fly-Fishing, Mikro Maketler',
  'Su Üstü Mikro Maketler, Döner Kaşık (Mepps), Çekirge (Fly)',
  'Melen Çayı, Karadeniz dereleri ve iç anadolu akarsuları',
  '2/5 Yıldız - Bol Kılçıklı',
  'Eti pek lezzetli olmadığı için Catch & Release (Yakala ve Bırak) yapılması en doğrusudur.',
  'Not highly valued for meat; Catch & Release is strongly encouraged.',
  'Taşlık ve akıntılı nehirlerde, köprü altlarında veya suya sarkan ağaç dallarının gölgesinde bekler. LRF ve Fly-fishing ile su üstü sahtelere yaptığı sert vuruşlar sebebiyle avı en zevkli tatlı su türlerindendir.',
  'Waits under overhanging trees or in river currents. Famous for its aggressive surface strikes, making it a top target for LRF and Fly-fishing.',
  NULL,
  TRUE
),
(
  'Kefal (Has Kefal)',
  'Flathead Grey Mullet',
  'Mugil cephalus',
  'Tuzlu Su',
  'Limanlarda ve nehir ağızlarında sıkça görülen, güçlü yüzücü.',
  'Strong swimmer frequently seen in ports and river estuaries.',
  'Asgari 20 cm',
  'Yıl boyu serbest',
  'İlkbahar, Yaz, Sonbahar',
  'Kıbrıs Sarması, Şamandıralı Takım',
  'Taze Ekmek İçi, Hamur, Sardalya Filetosu',
  'Limanlar, Marina içleri, Nehirlerin denize döküldüğü yerler',
  '3/5 Yıldız - Yaşadığı Suya Göre Değişir',
  'Temiz sulardan yakalananları fırında veya ızgarada çok lezzetli olur.',
  'Delicious baked or grilled if caught from clean waters.',
  'Çok ürkektir ve yemi hemen yutmaz, emer. Bu yüzden yakalaması tecrübe ister. Oltaya bindiğinde inanılmaz bir güçle fişekleyerek misinayı zorlar.',
  'Very skittish and sucks the bait rather than biting it. When hooked, it puts up a very strong and energetic fight.',
  NULL,
  TRUE
),
(
  'Lagos (Kumlagosu)',
  'White Grouper',
  'Epinephelus aeneus',
  'Tuzlu Su',
  'Akdeniz''in kayalık diplerinde yaşayan, trofe değeri çok yüksek dev.',
  'Giant trophy fish living in the rocky bottoms of the Mediterranean.',
  'Asgari 45 cm',
  '15 Nisan - 15 Temmuz (Ticari',
  'Yaz, Sonbahar',
  'Slow Jigging, Canlı Yemle Bırakma, Ağır Spin',
  'Canlı Kalamar, Sübye, Ağır Jig Sahteleri',
  'Akdeniz (Antalya, Taşucu, Hatay kıyıları)',
  '5/5 Yıldız - Muazzam Bir Et Kalitesi',
  'Şiş, ızgara veya fırında sebzeli kavurması yapılır.',
  'Prepared as skewers, grilled, or pan-roasted with vegetables.',
  'Gücüyle ekipmanları test eden bir balıktır. Yemi aldığında hızla kayaların arasına girip kendini kilitler, bu yüzden vuruş alındığında hiç boşluk vermeden dipten kesilmelidir.',
  'Tests equipment to its limits. When hooked, it immediately dives into rock crevices, requiring the angler to pull it up with zero slack.',
  NULL,
  TRUE
),
(
  'Mercan (Kırmızı Mercan)',
  'Common Pandora',
  'Pagellus erythrinus',
  'Tuzlu Su',
  'Derin suların taşlık ve kumluk alanlarında yaşayan pembe incisi.',
  'The pink pearl of deep rocky and sandy waters.',
  'Asgari 15 cm',
  'Yıl boyu serbest',
  'İlkbahar, Sonbahar',
  'Tekneden Yemli Dip Takımı (Sarkıtma)',
  'Karides, Sülünes, Kalamar Parçası, Madya',
  'Ege Denizi (Çeşme, Seferihisar, Ayvalık)',
  '5/5 Yıldız - Çok Lezzetli Beyaz Et',
  'Taze otlar ve zeytinyağı ile fırında veya odun ateşinde ızgarası yapılır.',
  'Baked with fresh herbs and olive oil or wood-grilled.',
  'Genellikle tekneden yapılan avların en değerli hedefidir. Sürü halinde gezerler, dipte yemi tırtıklayarak yer. Hassas uçlu tekne kamışları (boat rod) ile avlanması keyiflidir.',
  'Often the most prized target for boat fishing. Schools feed on the bottom. Best targeted with sensitive boat rods.',
  NULL,
  TRUE
);

-- =========================================================================
-- FISH WIKI - TOPLU BALIK EKLEME SQL SORGUSU (BÖLÜM 3: N - Z)
-- =========================================================================

INSERT INTO fishes (
  name_tr,
  name_en,
  scientific_name,
  water_type,
  short_info_tr,
  short_info_en,
  limit_size,
  ban_periods,
  active_seasons,
  recommended_gear,
  favorite_baits,
  primary_regions,
  taste_rating,
  cooking_tips_tr,
  cooking_tips_en,
  description_tr,
  description_en,
  image_url,
  is_active
) VALUES 
(
  'Orkinos (Mavi Kanat)',
  'Atlantic Bluefin Tuna',
  'Thunnus thynnus',
  'Tuzlu Su',
  'Açık denizlerin en hızlı ve en güçlü, trofe değeri en yüksek pelajik avcısı.',
  'The fastest, strongest, and most prized pelagic predator of the open seas.',
  'Asgari 115 cm veya 30 kg (Özel İzin Gerektirir)',
  'ICCAT kotalarına ve uluslararası yasalara tabidir',
  'Yaz, Sonbahar',
  'Big Game (Ağır Trolling), Heavy Spinning',
  'Canlı Uskumru, Palamut, Büyük Popper Sahteler',
  'Kuzey Ege (Saros), Akdeniz açıkları',
  '5/5 Yıldız - Eşsiz (Sushi/Sashimi kalitesi)',
  'Asla çok pişirilmemeli, ızgarada içi hafif pembe kalacak şekilde mühürlenmeli veya çiğ (sashimi) tüketilmelidir.',
  'Should never be overcooked; sear on the grill leaving the center pink, or serve raw as sashimi.',
  'Sportif balıkçılığın zirvesidir. Yakalanması devasa çıkrık makineler, çok güçlü kamışlar ve saatler süren fiziksel bir mücadele gerektirir.',
  'The pinnacle of sport fishing. Catching it requires massive reels, heavy rods, and hours of physical battle.',
  NULL,
  TRUE
),
(
  'Palamut',
  'Atlantic Bonito',
  'Sarda sarda',
  'Tuzlu Su',
  'Karadeniz ve Marmara''nın göçmen, yırtıcı ve sürüler halinde gezen efsanesi.',
  'Migratory, predatory schooling legend of the Black Sea and Marmara.',
  'Asgari 25 cm (Torik için 38 cm)',
  '15 Nisan - 31 Ağustos',
  'Sonbahar',
  'Sırtı (Trolling), Ağır Spin, Palamut Çaparisi',
  'Kaşıklar, Rapalalar, İri Tüylü Çapari',
  'İstanbul Boğazı, Karadeniz kıyıları',
  '4/5 Yıldız - Siyah Etli ve Yağlı',
  'Eylül ayında fırında veya ızgarada, daha sonra yağlandığında tavada da yapılır.',
  'Baked or grilled in September; pan-fried later in the season when it gets fatter.',
  'Eylül ayında Karadeniz''den Marmara''ya göçü başlar. Boğazda sırtı çekerek veya kıyıdan ağır kaşıklarla (spin) yapılan avcılığı çok bereketlidir.',
  'Migration starts in September. Trolling in the Bosphorus or shore spinning with heavy metal spoons are highly productive.',
  NULL,
  TRUE
),
(
  'Sargoz (Karagöz)',
  'White Seabream',
  'Diplodus sargus',
  'Tuzlu Su',
  'Kayalık bölgelerin siyah dikey çizgili, güçlü çeneli efendisi.',
  'Strong-jawed master of rocky shores, recognized by its black vertical stripes.',
  'Asgari 21 cm',
  'Yıl boyu serbest',
  'İlkbahar, Sonbahar',
  'Şamandıralı Takım, LRF, Yemli Dip',
  'Yengeç, Sülünes, Madya, Karides',
  'Ege ve Akdeniz kayalık kıyıları',
  '4/5 Yıldız - Beyaz ve Sıkı Et',
  'Fırında zeytinyağı ve limonla ya da mangalda bütün olarak pişirilir.',
  'Baked with olive oil and lemon, or grilled whole on charcoal.',
  'Kayalıkların arasında yaşadığı için avlanması zordur; takımı kayalara taktırmadan yemi ulaştırmak ustalık ister. LRF takımlarına harika kafa atar.',
  'Difficult to catch as they live among rocks. Provides a great head-banging fight on LRF setups.',
  NULL,
  TRUE
),
(
  'Sinarit',
  'Common Dentex',
  'Dentex dentex',
  'Tuzlu Su',
  'Ege ve Akdeniz taşlıklarının en agresif, devasa dişlere sahip kralı.',
  'The king of Aegean and Mediterranean rocky structures, known for its massive canine teeth.',
  'Asgari 35 cm (Günlük limit: 5 Kg)',
  'Yıl boyu serbest',
  'İlkbahar, Yaz',
  'Slow Jigging, Canlı Yem (Zoka)',
  'Canlı Sübye, Kalamar, Inchiku Jigler',
  'Ege Denizi açıkları (Çeşme, Ayvalık), Akdeniz',
  '5/5 Yıldız - Trofe Lezzet',
  'Fırında kaya tuzu altında pişirilmesi veya kiremitte yapılması meşhurdur.',
  'Famous for being baked under a rock salt crust or in a clay pot.',
  'Çok zeki ve güçlü bir balıktır. Oltaya yakalandığında ilk hamlesi misinayı kayalara sürtüp koparmak olur. Güçlü fluorocarbon lider misinalar şarttır.',
  'Very intelligent and powerful. Its first instinct when hooked is to rub the line against rocks, so strong fluorocarbon leaders are essential.',
  NULL,
  TRUE
),
(
  'Sudak (Uzun Levrek)',
  'Zander',
  'Sander lucioperca',
  'Tatlı Su',
  'Büyük baraj göllerinin vampir dişli, karanlığı seven zeki avcısı.',
  'Intelligent, vampire-toothed predator of large reservoir lakes, active in low light.',
  'Asgari 26 cm',
  '15 Mart - 30 Nisan (İç sularda)',
  'İlkbahar, Sonbahar',
  'Spinning, LRF, Jigging',
  'Silikon Yemler (Jighead), Canlı Gümüş Balığı',
  'Hirfanlı, Sarıyar ve diğer büyük baraj gölleri',
  '5/5 Yıldız - Tatlı Suyun En Lezzetlisi',
  'Kılçıksız löp et olduğu için fileto edilip tereyağında kızartılması eşsizdir.',
  'Yields boneless fillets; pan-frying in butter is unmatched.',
  'Gündüzleri derin sulara çekilir, sabah suyu ve akşam karanlığında sığlıklara avlanmaya çıkar. Silikon yemleri dipten zıplatarak (jigging) avlamak çok zevklidir.',
  'Retreats to deep water during the day, hunts in shallows at dawn and dusk. Catching them by bouncing soft plastics on the bottom is thrilling.',
  NULL,
  TRUE
),
(
  'Trança',
  'Pink Dentex',
  'Dentex gibbosus',
  'Tuzlu Su',
  'Sinarit''in akrabası olan, kafası hörgüçlü derin su trofesi.',
  'A relative of the Dentex, this deep-water trophy features a distinctive head hump.',
  'Asgari 35 cm',
  'Yıl boyu serbest',
  'İlkbahar, Yaz',
  'Derin Su Jigging, Parakete',
  'Canlı Kalamar, Sübye',
  'Ege (Gökçeada, Çanakkale açıkları)',
  '5/5 Yıldız - Çok Yüksek Kalite',
  'Dilimlenip ızgarada veya sebzelerle fırında pişirilir.',
  'Steaked and grilled, or baked with vegetables.',
  'Derin taşlıkların etrafında gezer. Yaşı ilerledikçe kafasında karakteristik bir hörgüç oluşur. Tekne avcılarının en büyük hayallerinden biridir.',
  'Roams around deep rocky structures. Develops a characteristic head hump as it ages. A top dream catch for boat anglers.',
  NULL,
  TRUE
),
(
  'Turna',
  'Northern Pike',
  'Esox lucius',
  'Tatlı Su',
  'Sazlıkların arasına gizlenen, tatlı suların kamuflajlı tatlı su timsahı.',
  'The freshwater crocodile; a camouflaged ambush predator hiding among reeds.',
  'Asgari 40 cm (Günlük limit: 5 Adet)',
  '15 Aralık - 31 Mart (Üreme dönemi)',
  'İlkbahar, Sonbahar',
  'Spinning (At-Çek)',
  'Döner Kaşık (Mepps 3-4-5), Sasi (Silikon), Maket Balıklar',
  'İç Anadolu ve Marmara''daki göller, sazlık göletler, Terkos',
  '3/5 Yıldız - Lezzetli Fakat Kılçıklı',
  'Y şeklinde kılçıkları vardır, tulum çıkarılıp kızartılması veya köftesi önerilir.',
  'Has Y-shaped bones; best skinned and fried, or minced for patties.',
  'Otluk ve sazlık kenarlarında pusu kurup avına aniden saldırır. Keskin dişleri misinayı kolayca kestiği için avında mutlaka çelik tel (wire leader) kullanılmalıdır.',
  'Ambush predator that attacks suddenly from weeds. A steel wire leader is absolutely mandatory due to its razor-sharp teeth.',
  NULL,
  TRUE
),
(
  'Uskumru',
  'Atlantic Mackerel',
  'Scomber scombrus',
  'Tuzlu Su',
  'Sırtındaki kaplan desenleri ile bilinen, yağlı ve sürü halinde gezen pelajik tür.',
  'Pelagic schooling species known for its tiger-striped back and oily meat.',
  'Asgari 20 cm',
  'Yıl boyu serbest',
  'Sonbahar, Kış',
  'Çapari, Hafif Spin',
  'Tüylü Çapari, Küçük Metal Jigler',
  'Marmara, Çanakkale Boğazı, Karadeniz',
  '5/5 Yıldız - Çok Sağlıklı ve Yağlı',
  'Kurutularak çirozu yapılır, ızgarası efsanedir.',
  'Traditionally sun-dried as "çiroz" or perfectly grilled.',
  'Kolyoz ile çok karıştırılır (Uskumrunun gözü daha küçüktür). Marmara''da eskisi kadar çok görülmese de yakalandığında çok hareketli bir av sunar.',
  'Often confused with Chub Mackerel. Though less common in Marmara now, it offers a very energetic fight when hooked.',
  NULL,
  TRUE
),
(
  'Yayın Balığı',
  'Wels Catfish',
  'Silurus glanis',
  'Tatlı Su',
  'Tatlı sularımızın en büyüğü; uzun bıyıklı, pulsuz, devasa dip canavarı.',
  'The largest in our freshwaters; a giant, scaleless bottom monster with long barbels.',
  'Asgari 90 cm',
  '15 Mart - 15 Haziran',
  'Yaz (Özellikle sıcak yaz geceleri)',
  'Ağır Dip Takımı (Catfish Rig), Clonk (Şaplak)',
  'Canlı Balık (Kızılkanat vs.), İri Solucan Demeti, Tavuk Ciğeri, Sülük',
  'Sakarya Nehri, Kızılırmak, Seyhan Nehri',
  '4/5 Yıldız - Kılçıksız, Tavuk Eti Gibi',
  'Kalın dilimler halinde kesilip şişte mangalı veya mısır unlu tavası yapılır.',
  'Cut into thick steaks for skewers on the grill, or pan-fried with cornmeal.',
  'Akarsularda kamp avcılığı yapanların rüyasıdır. Gece beslenir, titreşime ve kokuya çok duyarlıdır. Büyüklüğü 2 metreyi, ağırlığı 100 kiloyu geçebilir.',
  'A dream for river campers. Nocturnal and highly sensitive to vibration and smell. Can grow over 2 meters and 100 kg.',
  NULL,
  TRUE
),
(
  'Zargana',
  'Garfish',
  'Belone belone',
  'Tuzlu Su',
  'İnce uzun gagasıyla su yüzeyinde gezen, kılıç şeklindeki kıyı balığı.',
  'Sword-shaped coastal fish with a long beak, cruising the surface.',
  'Limit Yok (Sportif sınır bulunmuyor)',
  'Yıl boyu serbest',
  'Yaz, Sonbahar',
  'Şamandıralı Top (Zargana Topu), İnce LRF',
  'İpek (Turuncu/Sarı), Gümüş Balığı, Kuyruk Altı, Midye Kenarı',
  'Tüm kıyılar (Marmara, Ege, Karadeniz, Akdeniz)',
  '3/5 Yıldız - Fosforlu Yeşil Kılçıklı',
  'Kılçıkları yeşil renklidir, zehirli değildir. Tavada bütün olarak kızartılır.',
  'Has harmless fluorescent green bones. Pan-fried whole.',
  'Özellikle sonbaharda kıyılardan zargana topu arkasına bağlanan iğnesiz ipek (sadece dişlerine takılır) ile avlanması çok meşhurdur. Su yüzeyinde zıplayarak muazzam bir görsel şölen sunar.',
  'Famous for being caught with hookless silk threads (which tangle in their teeth) trailed behind a float. Provides a visual spectacle by jumping across the surface.',
  NULL,
  TRUE
);