-- ====================================================================
-- OLTAPP: Eksik balık ekleme (foto harici)
-- Mevcutta olan kayıtlar tekrar eklenmez.
-- Eşleştirme: scientific_name veya name_tr
-- ====================================================================

WITH new_fishes AS (
  SELECT *
  FROM (
    VALUES
      ('Kolyoz', 'Chub Mackerel', 'Scomber colias', 'Tuzlu Su', 'Yaz, Sonbahar', 'Çapari, Hafif Spin', 'Uskumruya benzeyen, daha iri gözlü ve çok hızlı sürü balığıdır.', 'Very fast schooling fish similar to mackerel, distinguished by its larger eyes.', 'Asgari 18 cm', 'Yıl boyu serbest', 'Marmara ve Ege''de sürüler halinde gezen ekonomik pelajik tür.', 'Economic pelagic species schooling in Marmara and Aegean waters.', 'Tüylü Çapari, Mikro Jig', 'Marmara, Ege, Çanakkale Boğazı', '4/5 Yıldız - Yağlı', 'Izgarada ve tavada çok uygundur.', 'Excellent for grill and pan frying.'),
      ('İzmarit', 'Picarel', 'Spicara smaris', 'Tuzlu Su', 'İlkbahar, Yaz, Sonbahar', 'İnce Çapari, LRF', 'Kıyılarda sürü gezen, hafif takımla keyifli av veren küçük pelajik tür.', 'Small pelagic species schooling near shores and fun on light tackle.', 'Asgari 13 cm', 'Yıl boyu serbest', 'Kıyı balıkçılığında sık yakalanan sürü balığı.', 'Common schooling catch in coastal fishing.', 'Çapari, Küçük Silikon', 'Ege, Marmara, Akdeniz kıyıları', '3/5 Yıldız - Hafif Et', 'Genellikle tava yapılır.', 'Usually pan-fried.'),
      ('İspari', 'Annular Seabream', 'Diplodus annularis', 'Tuzlu Su', 'İlkbahar, Yaz', 'Şamandıralı Takım, LRF', 'Kıyı kayalıklarında yaşayan, sürü yapan ve hassas vuruş veren küçük çipura akrabasıdır.', 'Small bream relative schooling around rocky coasts with subtle bites.', 'Asgari 16 cm', 'Yıl boyu serbest', 'Kıyı taşlıklarında sık görülen sarı halkalı tür.', 'Yellow-ringed species often found on rocky shores.', 'Mamun, Boru Kurdu', 'Ege ve Akdeniz kıyıları', '3/5 Yıldız - Yumuşak Et', 'Tava için uygundur.', 'Good for pan frying.'),
      ('Melanur', 'Saddled Seabream', 'Oblada melanura', 'Tuzlu Su', 'Yaz, Sonbahar', 'Şamandıra, LRF, Hafif Spin', 'Kuyruk dibindeki siyah benekle tanınır, yüzeyde aktif gezer.', 'Recognized by the black saddle near tail; often active near surface.', 'Asgari 18 cm', 'Yıl boyu serbest', 'Açık kıyı ve adalarda sürü gezen hızlı tür.', 'Fast schooling species around open coasts and islands.', 'Ekmek, Küçük Silikon, Karides', 'Ege adaları ve Akdeniz kıyıları', '3/5 Yıldız - Orta Lezzet', 'Tava ve ızgarada yapılabilir.', 'Suitable for pan or grill.'),
      ('Kılıç Balığı', 'Swordfish', 'Xiphias gladius', 'Tuzlu Su', 'Yaz, Sonbahar', 'Big Game Trolling', 'Açık denizde yaşayan, yüksek hızla avlanan büyük pelajik avcı.', 'Large open-ocean predator known for high-speed attacks.', 'Asgari 125 cm (yasal düzenlemeye göre)', 'Kotaya ve sezona tabidir', 'Açık denizlerin en güçlü göçmen avcılarından biri.', 'One of the strongest migratory predators of open seas.', 'Canlı Yem, Trolling Yemleri', 'Akdeniz açıkları', '5/5 Yıldız - Değerli Et', 'Kalın dilimler ızgarada pişirilir.', 'Thick steaks are grilled.'),
      ('Lahos', 'Goldblotch Grouper', 'Epinephelus costae', 'Tuzlu Su', 'Yaz, Sonbahar', 'Yemli Dip, Slow Jigging', 'Taşlık diplerde yaşayan güçlü bir lahos türüdür.', 'Strong grouper species inhabiting rocky bottoms.', 'Asgari 45 cm', 'Bölgesel kısıtlamalar kontrol edilmeli', 'Akdeniz taşlıklarında yaşayan trofe dip avcısı.', 'Trophy bottom predator from Mediterranean reefs.', 'Canlı Kalamar, Sübye', 'Akdeniz kıyıları', '5/5 Yıldız - Üst Düzey', 'Fırın ve ızgarada çok başarılıdır.', 'Excellent baked or grilled.'),
      ('Lipsos', 'Painted Comber', 'Serranus scriba', 'Tuzlu Su', 'İlkbahar, Yaz', 'LRF, Hafif Dip Takımı', 'Kayalık kıyılarda yaşayan renkli, küçük ama agresif yırtıcı.', 'Colorful small but aggressive predator on rocky coasts.', 'Limit Yok (yerel kuralları kontrol et)', 'Yıl boyu serbest', 'LRF avlarında sık gelen çizgili dip balığı.', 'Striped bottom fish commonly caught in LRF sessions.', 'Karides, Mikro Silikon', 'Ege ve Akdeniz', '2/5 Yıldız - Küçük Boy', 'Genelde sportif amaçlı tutulur.', 'Mostly targeted for sport.'),
      ('Hani Balığı', 'Comber', 'Serranus cabrilla', 'Tuzlu Su', 'İlkbahar, Yaz, Sonbahar', 'LRF, Yemli Dip', 'Küçük boyutuna rağmen sert vuruş yapan dip yırtıcısı.', 'Bottom predator with hard strikes despite small size.', 'Limit Yok', 'Yıl boyu serbest', 'Kıyı kayalıklarında sık rastlanan yerel tür.', 'Common local species on rocky coasts.', 'Karides, Tavuk Göğsü, Silikon', 'Ege, Akdeniz, Marmara', '2/5 Yıldız - Düşük Et Verimi', 'Tava yapılabilir.', 'Can be pan-fried.'),
      ('Mırmır', 'Striped Seabream', 'Lithognathus mormyrus', 'Tuzlu Su', 'Yaz, Sonbahar', 'Surfcasting, İnce Dip Takımı', 'Kumluk sahillerde gece avlarında çok verimli hedef türdür.', 'Highly productive target for night surfcasting on sandy beaches.', 'Asgari 15 cm', 'Yıl boyu serbest', 'Kumluk kıyıların çizgili dip balığı.', 'Striped bottom fish of sandy coasts.', 'Boru Kurdu, Sülünes', 'Ege, Akdeniz, Marmara', '4/5 Yıldız - Beyaz Et', 'Fırın ve ızgaraya uygundur.', 'Good for baking and grilling.'),
      ('Kefal (Altınbaş)', 'Golden Grey Mullet', 'Chelon auratus', 'Tuzlu Su', 'İlkbahar, Yaz, Sonbahar', 'Şamandıralı Takım, Kıbrıs Sarması', 'Liman ve dere ağızlarında gezen ürkek kefal türü.', 'Skittish mullet species common in harbors and estuaries.', 'Asgari 20 cm', 'Yıl boyu serbest', 'Altın tonlu baş yapısıyla ayrışan kefal türü.', 'Mullet species distinguished by golden-toned head.', 'Ekmek, Hamur, Karides', 'Marmara, Ege, Akdeniz', '3/5 Yıldız - Orta Yağlı', 'Temiz sularda ızgara lezzetlidir.', 'Tasty grilled when caught in clean waters.'),
      ('Tatlı Su Turnası', 'Muskellunge (analog)', 'Esox masquinongy', 'Tatlı Su', 'Yaz, Sonbahar', 'Spinning, Büyük Silikon', 'Büyük sahteye sert vuran, iri yırtıcı profilindeki turna benzeri tür.', 'Large predatory profile species striking hard on big lures.', 'Asgari 50 cm', 'Üreme dönemi koruması uygulanmalı', 'Baraj göllerinde trofe odaklı avlanan iri yırtıcı sınıfı.', 'Trophy-class predator profile for reservoirs.', 'Büyük Jerkbait, Shad', 'Büyük baraj gölleri', '3/5 Yıldız - Sportif', 'Genelde yakala-bırak önerilir.', 'Catch-and-release is generally recommended.'),
      ('Kefal (Dudaklı)', 'Thicklip Grey Mullet', 'Chelon labrosus', 'Tuzlu Su', 'İlkbahar, Yaz', 'Şamandıralı Takım', 'Kalın dudak yapısı ile ayrılan, yem seçici kefal türüdür.', 'Selective-feeding mullet species known for thick lips.', 'Asgari 20 cm', 'Yıl boyu serbest', 'Kıyı ve lagünlerde görülen güçlü yüzücü.', 'Strong swimmer found in coasts and lagoons.', 'Ekmek, Hamur', 'Ege lagünleri ve kıyılar', '3/5 Yıldız - Orta', 'Tava/ızgara yapılabilir.', 'Suitable for pan and grill.'),
      ('Berlam', 'European Hake', 'Merluccius merluccius', 'Tuzlu Su', 'Kış, İlkbahar', 'Derin Su Dip Takımı', 'Derin sularda yaşayan, beyaz etli değerli dip balığı.', 'Valuable deep-water fish with white meat.', 'Asgari 25 cm', 'Sezonsal kısıtlamalar kontrol edilmeli', 'Derin deniz avcılığında önemli ekonomik tür.', 'Important economic species in deep-sea fishing.', 'Kalamar, Sardalya', 'Ege ve Akdeniz derin suları', '5/5 Yıldız - Beyaz Et', 'Fileto olarak fırın veya tavada pişirilir.', 'Cooked as fillet in oven or pan.'),
      ('Lapa', 'Black Seabream', 'Spondyliosoma cantharus', 'Tuzlu Su', 'İlkbahar, Sonbahar', 'Yemli Dip, Şamandıra', 'Taşlık diplerde yaşayan, orta boylu çipura akrabası.', 'Mid-sized bream relative living on rocky bottoms.', 'Asgari 20 cm', 'Yıl boyu serbest', 'Kıyı kayalıklarında sürüler halinde dolaşır.', 'Forms schools around rocky coastal structures.', 'Mamun, Midye, Karides', 'Marmara, Ege, Akdeniz', '4/5 Yıldız - Sıkı Et', 'Izgara için uygundur.', 'Suitable for grilling.'),
      ('Gümüşi Havuz Balığı', 'Prussian Carp', 'Carassius gibelio', 'Tatlı Su', 'İlkbahar, Yaz, Sonbahar', 'Şamandıralı Takım, Feeder', 'İstilacı özellik gösteren, çoğalma hızı yüksek tatlı su türüdür.', 'Invasive freshwater species with high reproduction rate.', 'Limit Yok (yerel düzenlemeye bakılmalı)', 'Yıl boyu serbest', 'Birçok göl ve gölette yaygın istilacı tür.', 'Widely distributed invasive species in many lakes and ponds.', 'Mısır, Solucan, Hamur', 'İç Anadolu ve Marmara göl-göletleri', '2/5 Yıldız - Kılçıklı', 'Tüketimden çok popülasyon kontrolü için avlanır.', 'Often targeted for population control rather than consumption.'),
      ('Kaya Balığı', 'Black Goby', 'Gobius niger', 'Tuzlu Su', 'Yaz, Sonbahar', 'LRF, Dip Takımı', 'Kıyı taşlıklarında yaşayan küçük dip türü.', 'Small bottom-dwelling species on rocky shores.', 'Limit Yok', 'Yıl boyu serbest', 'Taş aralarında saklanan minik bölgeci balık.', 'Tiny territorial fish hiding among rocks.', 'Küçük Karides, Mikro Yem', 'Marmara ve Ege kıyıları', '1/5 Yıldız - Düşük Et', 'Genelde tüketilmez.', 'Rarely consumed.'),
      ('Lambuka', 'Common Dolphinfish', 'Coryphaena hippurus', 'Tuzlu Su', 'Yaz', 'Trolling, Big Game Spinning', 'Açık denizde çok hızlı büyüyen ve sert mücadele veren pelajik avcı.', 'Fast-growing open-ocean pelagic predator with explosive fights.', 'Asgari 60 cm (yerel kurala göre)', 'Kota ve sezon kontrolü gerekir', 'Yaz aylarında açık denizde görülen göçer tür.', 'Migratory species observed offshore in summer.', 'Canlı Yem, Yüzey Sahteleri', 'Akdeniz açıkları', '4/5 Yıldız - Sıkı Et', 'Izgara ve marine için uygundur.', 'Good for grilling and marinating.')
  ) AS t(
    name_tr, name_en, scientific_name, water_type, active_seasons, recommended_gear,
    description_tr, description_en, limit_size, ban_periods, short_info_tr, short_info_en,
    favorite_baits, primary_regions, taste_rating, cooking_tips_tr, cooking_tips_en
  )
)
INSERT INTO public.fishes (
  name_tr, name_en, scientific_name, water_type, active_seasons, recommended_gear,
  description_tr, description_en, image_url, is_active, created_at, limit_size, ban_periods,
  short_info_tr, short_info_en, favorite_baits, primary_regions, taste_rating, cooking_tips_tr, cooking_tips_en
)
SELECT
  nf.name_tr, nf.name_en, nf.scientific_name, nf.water_type, nf.active_seasons, nf.recommended_gear,
  nf.description_tr, nf.description_en, NULL, true, timezone('utc'::text, now()), nf.limit_size, nf.ban_periods,
  nf.short_info_tr, nf.short_info_en, nf.favorite_baits, nf.primary_regions, nf.taste_rating, nf.cooking_tips_tr, nf.cooking_tips_en
FROM new_fishes nf
WHERE NOT EXISTS (
  SELECT 1
  FROM public.fishes f
  WHERE lower(f.scientific_name) = lower(nf.scientific_name)
     OR lower(f.name_tr) = lower(nf.name_tr)
);

NOTIFY pgrst, 'reload schema';
