-- =========================================================================
-- EKSİK TATLI SU BALIKLARI EKLEME SQL SORGUSU
-- =========================================================================

INSERT INTO public.fishes (
  name_tr,
  name_en,
  scientific_name,
  water_type,
  short_info_tr,
  short_info_en,
  limit_size,
  ban_periods,
  active_seasons,
  recommended_gear,
  favorite_baits,
  primary_regions,
  taste_rating,
  cooking_tips_tr,
  cooking_tips_en,
  description_tr,
  description_en,
  image_url,
  is_active
) VALUES 
(
  'Fırat Turnası',
  'Manger (Barbus)',
  'Luciobarbus esocinus',
  'Tatlı Su',
  'Fırat ve Dicle nehirlerinin 100 kg''a ulaşabilen dev efsanevi avcısı.',
  'Legendary giant predator of the Euphrates and Tigris rivers reaching up to 100 kg.',
  'Asgari 50 cm',
  '15 Mart - 15 Haziran',
  'İlkbahar, Yaz, Sonbahar',
  'Ağır Dip Oltası, Kaşık, Canlı Yem Düzenekleri',
  'Canlı Balık, Hamur, Ağır Metal Kaşıklar, Sülük',
  'Atatürk Barajı, Keban Barajı, Birecik, Fırat ve Dicle Nehirleri',
  '4/5 Yıldız - İri ve Yağlı Et',
  'Fırında baharatlı buğulama veya kuşbaşı doğranıp şiş kebap yapılır.',
  'Best oven-baked with herbs or grilled as skewers.',
  'Güneydoğu ve Doğu Anadolu sularının en büyük trofe balığıdır. Oltaya bindiğinde bükülmez bir direnç gösterir ve ağır takımlarla avlanır.',
  'The largest trophy freshwater species of the Euphrates basin, known for its massive power.',
  'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
  TRUE
),
(
  'Kırmızı Benekli Alabalık',
  'Brown Trout',
  'Salmo trutta fario',
  'Tatlı Su',
  'Dağ derelerinin ve buz gibi kaynak sularının yerli kraliçesi.',
  'The native queen of cold mountain streams and spring waters.',
  'Asgari 20 cm (Günlük limit: 3 Adet)',
  '1 Ekim - 28 Şubat (Orman içi sularda)',
  'İlkbahar, Yaz',
  'Fly-fishing, Ultra Light LRF, Mepps Kaşık (0-1 No)',
  'Suni Sinek (Dry/Nymph), Mikro Kaşıklar, Küçük Silikonlar',
  'Doğu Karadeniz dereleri, Toros dağ dereleri, Munzur, Kaçkarlar',
  '5/5 Yıldız - Müthiş Lezzet ve Kırmızı Et',
  'Tereyağında hafifçe tavada kızartılır veya kiremitte fırınlanır.',
  'Best pan-fried in fresh butter or clay pot baked.',
  'Buz gibi berrak derelerde yaşamını sürdüren, inanılmaz ürkek ve zeki bir alabalık türüdür. Sinek oltası (Fly fishing) sporu için en değerli balıktır.',
  'An extremely wary and intelligent native trout, highly prized by fly anglers.',
  'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=800&q=80',
  TRUE
),
(
  'Tatlı Su Levreği (Perç)',
  'European Perch',
  'Perca fluviatilis',
  'Tatlı Su',
  'Çizgili vücudu ve turuncu yüzgeçleriyle göllerin obur avcısı.',
  'A voracious lake predator with tiger stripes and bright orange fins.',
  'Asgari 18 cm',
  '15 Mart - 30 Nisan',
  'İlkbahar, Yaz, Sonbahar',
  'LRF (Light Rock Fishing), Döner Kaşık, Silikon Sahteler',
  'Mikro Silikonlar (2-5cm), Döner Kaşıklar (Mepps 1-2 No), Canlı Gümüş Balığı',
  'Sapanca Gölü, Terkos Gölü, Uluabat, Eğirdir, İç Anadolu gölleri',
  '4/5 Yıldız - Beyaz ve Sıkı Et',
  'Derisi yüzüldükten sonra mısır ununa bulanıp tavada çıtır kızartılır.',
  'Skin removed, coated in cornmeal and pan-fried crispy.',
  'Sürü halinde gezen ve mikro yemlere gözü kapalı atlayan çok keyifli bir LRF balığıdır. Dikenli sırt yüzgecine dikkat edilmelidir.',
  'Schooling lake predators that offer non-stop action on ultralight lures.',
  'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?auto=format&fit=crop&w=800&q=80',
  TRUE
),
(
  'Şabut Balığı',
  'Euphrates Barbel',
  'Arabibarbus grypus',
  'Tatlı Su',
  'Mezopotamya sularına özgü lezzeti ve gücüyle ünlü bıyıklı balık.',
  'A powerful barbell species native to Mesopotamian waters.',
  'Asgari 30 cm',
  '15 Mart - 15 Haziran',
  'İlkbahar, Yaz',
  'Sazan Montajı, Yemli Dip Oltası',
  'Haşlanmış Mısır, Özel Sazan Hamurları, Solucan, Yengeç',
  'Fırat ve Dicle Nehri, Atatürk Barajı, Keban Barajı, Birecik',
  '5/5 Yıldız - Yörenin En Lezzetli Balığı',
  'Izgarada meşe kömüründe pişirilir veya fırında sebzeli buğulama yapılır.',
  'Grilled over charcoal or baked with fresh vegetables.',
  'Fırat ve Dicle nehrinde yaşayan, pullu ve bıyıklı yapısıyla yüksek ekonomik ve lezzet değerine sahip endemik bir tatlı su türüdür.',
  'An endemic barbel species highly valued for its gastronomy and fighting power.',
  'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
  TRUE
),
(
  'Kızılkanat',
  'Rudd',
  'Scardinius erythrophthalmus',
  'Tatlı Su',
  'Parlak kırmızı yüzgeçleri ve gümüş gövdesiyle sazlıkların sevimli sakini.',
  'Beautiful silver fish with bright red fins inhabiting reed beds.',
  'Asgari 15 cm',
  '15 Mart - 15 Haziran',
  'Şamandıralı İnce Takım, LRF',
  'Ekmek İçi, Solucan, Mısır, Küçük Sinek Sahteleri',
  'Sapanca, Terkos, Uluabat, Manyas ve tüm göl sazlıkları',
  '3/5 Yıldız - Kılçıklı Ancak Tatlı Et',
  'Tavada ince çizikler atılarak bol yağda kızartılır.',
  'Deep fried with cross cuts along the body.',
  'Durgun ve bitkili göllerde şamandıralı oltalarla avlanması özellikle genç balıkçılar için çok keyifli olan tatlı su balığıdır.',
  'A classic float-fishing species found in vegetated freshwater lakes.',
  'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
  TRUE
),
(
  'Kadife Balığı',
  'Tench',
  'Tinca tinca',
  'Tatlı Su',
  'Koyu yeşil kadifemsi pul yapısı ve hassas ısırıklarıyla ünlü dip sakini.',
  'Dark green velvet-skinned bottom dweller known for subtle bites.',
  'Asgari 26 cm',
  '15 Mart - 15 Haziran',
  'Hassas Şamandıralı Takım, Dip Oltası',
  'Solucan, Kırmızı Kurt, Haşlanmış Mısır, Ekmek İçi',
  'İznik Gölü, Mogan Gölü, Abant, Göller Bölgesi durgun sularda',
  '3/5 Yıldız - Yumuşak ve Yağlı Et',
   meşe odununda ızgarada veya tavada pişirilir.',
  'Grilled over oak charcoal or pan-fried.',
  'Çamurlu ve sazlık diplerde yaşayan, vücudu koruyucu kaygan bir tabakayla kaplı çok uyanık bir dip balığıdır.',
  'A cautious bottom feeding fish living in muddy reed beds.',
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80',
  TRUE
),
(
  'Yılan Balığı',
  'European Eel',
  'Anguilla anguilla',
  'Tatlı Su',
  'Denizlerden nehirlere göç eden son derece güçlü ve yağlı yılanımsı balık.',
  'Catadromous snake-like fish migrating between oceans and freshwaters.',
  'Asgari 50 cm',
  'Yıl boyu serbest',
  'Gece Yemli Dip Oltası',
  'Canlı Balık, Sülük, Solucan, Balık Parçaları',
  'Manavgat Nehir Ağzı, Köyceğiz Gölü, Sakarya Nehri, Asi Nehri',
  '5/5 Yıldız - Çok Yüksek Yağ Oranı ve Güçlü Lezzet',
  'Izgarada kömür ateşinde kendi yağında pişirilir veya füme yapılır.',
  'Grilled over charcoal in its own natural fat or smoked.',
  'Okyanusta doğup tatlı su nehirlerimize göç eden, gece kayalık ve çamurlu diplerde yemli oltalarla yakalanan egzotik bir türdür.',
  'An exotic catadromous species targeted at night with heavy bottom bait rigs.',
  'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?auto=format&fit=crop&w=800&q=80',
  TRUE
);
