import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error('Missing Supabase credentials');
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseAnonKey);

const ALL_ARTICLES = [
  // RIGS
  { category: 'rigs', title_tr: 'Hair Rig', title_en: 'Hair Rig', short_desc_tr: 'Yemi iğneden bağımsız sunan en temel sazan rigi.', short_desc_en: 'Classic carp hair rig presentation.', content_tr: 'Hair Rig; yemin iğneye doğrudan takılmak yerine iğne altındaki kıl misinaya dizilerek balığın temkinsiz emmesini sağlayan temel sazan montajıdır.', content_en: 'Classic hair rig.', image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'Başlangıç', is_active: true },
  { category: 'rigs', title_tr: 'Ronnie Rig / Spinner Rig', title_en: 'Ronnie Rig', short_desc_tr: 'Pop-up yüzen yemlerde 360 derece dönebilen en popüler agresif sazan rigi.', short_desc_en: '360 degree rotating pop-up rig.', content_tr: 'Ronnie Rig; pop-up yemlerin dipteki otlardan 2-4 cm yukarıda askıda durmasını sağlayan ve iğneye 360 derece serbest dönüş vererek harika kanca tutuşu sunan rigdir.', content_en: 'Pop-up spinner rig.', image_url: 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'Orta', is_active: true },
  { category: 'rigs', title_tr: 'Chod Rig', title_en: 'Chod Rig', short_desc_tr: 'Çamurlu ve otlu zeminlerde pop-up yemin otların üstünde temiz kalmasını sağlayan rig.', short_desc_en: 'Silt and weed pop-up rig.', content_tr: 'Chod Rig; kurşun çamura veya tortuya gömülse bile sert fluorocarbon yemin otların üzerinde tertemiz askıda kalmasını sağlar.', content_en: 'Chod rig for silt.', image_url: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'İleri', is_active: true },
  { category: 'rigs', title_tr: 'Blowback Rig', title_en: 'Blowback Rig', short_desc_tr: 'Boilie yemin halka üzerinde serbest hareket etmesini sağlayan rig.', short_desc_en: 'Free sliding ring rig.', content_tr: 'Blowback Rig; sazan yemi dışarı üflemeye çalıştığında yemin halka üzerinde kayarak iğnenin ağızda takılı kalmasını sağlar.', content_en: 'Blowback rig.', image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'Orta', is_active: true },
  { category: 'rigs', title_tr: 'Snowman Rig', title_en: 'Snowman Rig', short_desc_tr: 'Batan boilie ve yüzen pop-up kombinasyonu nötr dengeli kardan adam rigi.', short_desc_en: 'Neutral balanced snowman presentation.', content_tr: 'Snowman Rig; batan boilie üzerine yüzen pop-up dizilerek yem nötr dengeli hale getirilir.', content_en: 'Snowman presentation.', image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'Başlangıç', is_active: true },
  { category: 'rigs', title_tr: 'Zig Rig', title_en: 'Zig Rig', short_desc_tr: 'Yazın orta suda ve yüzey altında askıda yüzen sazanları avlamak için uzun rig.', short_desc_en: 'Mid-water and surface carp rig.', content_tr: 'Zig Rig; sıcak havalarda dibe yatmayan sazanları orta su kolonunda (1-3 metre yukarıda) avlamak için sünger yemle hazırlanan uzun rigdir.', content_en: 'Midwater zig rig.', image_url: 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'Orta', is_active: true },
  { category: 'rigs', title_tr: 'Method Hair Rig', title_en: 'Method Hair Rig', short_desc_tr: 'Method feeder yemlik etrafına sarılan hamur ortasında kısa 8-10cm hızlı kanca rigi.', short_desc_en: 'Short feeder hair rig.', content_tr: 'Method Feeder Rig; yemlik etrafındaki hamurun dağılmasıyla yemin tam merkezde balığa sunulmasını sağlar.', content_en: 'Method feeder rig.', image_url: 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'Başlangıç', is_active: true },
  { category: 'rigs', title_tr: 'KD Rig', title_en: 'KD Rig', short_desc_tr: 'Temkinli balıklarda agresif kanca açısı sağlayan rig.', short_desc_en: 'Aggressive hooking carp rig.', content_tr: 'KD Rig; iğne gözünün hemen altından çıkan kıl sayesinde iğnenin uç kısmının ağır basarak alt dudağa hızlı saplanmasını sağlar.', content_en: 'KD rig.', image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'Orta', is_active: true },
  { category: 'rigs', title_tr: 'D Rig & Slip D Rig', title_en: 'D Rig', short_desc_tr: 'Pop-up ve wafter sunumunda doğal duruş ve kanca tutuşu sağlayan rig.', short_desc_en: 'D loop presentation rig.', content_tr: 'D Rig; D şeklinde oluşturulan halkanın üzerinde yemin kayarak kancanın batmasını kolaylaştırdığı mükemmel bir montajdır.', content_en: 'D-rig.', image_url: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'Orta', is_active: true },
  { category: 'rigs', title_tr: 'Combi Rig', title_en: 'Combi Rig', short_desc_tr: 'Sert ve yumuşak misinanın birleşimi ile takılmayı önleyen rig.', short_desc_en: 'Combined stiff and soft braid rig.', content_tr: 'Combi Rig; atışta dolaşmayı önleyen sert arka misina ile doğal haraketi sağlayan yumuşak ön misinayı birleştirir.', content_en: 'Combi rig.', image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'İleri', is_active: true },

  // KNOTS
  { category: 'knots', title_tr: 'FG Knot (İp + Lider Düğümü)', title_en: 'FG Knot', short_desc_tr: 'İp misina ile Fluorocarbon lider birleştirmede sıfır pürüzlü en güçlü düğüm.', short_desc_en: 'Slimmest braid to leader knot.', content_tr: 'FG Knot; ip misinanın lider etrafına örülmesiyle atılan, porselen fincanlardan takılmadan geçen rakipsiz düğümdür.', content_en: 'FG knot.', image_url: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', water_type: 'Tüm Sular', difficulty_level: 'İleri', is_active: true },
  { category: 'knots', title_tr: 'Alberto Knot (Crazy Alberto)', title_en: 'Alberto Knot', short_desc_tr: 'İp ile lider misinayı sahada çok hızlı ve pratik birleştiren düğüm.', short_desc_en: 'Fast braid to leader knot.', content_tr: 'Alberto Knot; rüzgarlı havalarda ve geceleri hızlıca atılabilen yüksek çekergüçlü lider düğümüdür.', content_en: 'Alberto knot.', image_url: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', water_type: 'Tüm Sular', difficulty_level: 'Orta', is_active: true },
  { category: 'knots', title_tr: 'Knotless Knot (Düğümsüz Düğüm)', title_en: 'Knotless Knot', short_desc_tr: 'Sazan balıkçılığında Hair Rig hazırlamak için kanca sapına sarılan düğüm.', short_desc_en: 'Essential knot for carp hair rigs.', content_tr: 'Knotless Knot; sazan iğne sapı etrafına 7-8 tur sarılarak Hair Rig oluşturan kolay ve güçlü düğümdür.', content_en: 'Knotless knot.', image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', water_type: 'Tatlı Su', difficulty_level: 'Başlangıç', is_active: true },
  { category: 'knots', title_tr: 'Palomar Knot', title_en: 'Palomar Knot', short_desc_tr: 'Klips, fırdöndü ve iğnelere misina bağlamada %95+ çeker güçlü en güvenilir düğüm.', short_desc_en: 'Strongest knot for terminal tackle.', content_tr: 'Palomar Knot; ip ve misinaların klipse ve fırdöndüye kaymadan baglanmasını sağlayan en sağlam düğümdür.', content_en: 'Palomar knot.', image_url: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', water_type: 'Tüm Sular', difficulty_level: 'Başlangıç', is_active: true },
  { category: 'knots', title_tr: 'Uni Knot & Double Uni', title_en: 'Uni Knot', short_desc_tr: 'Evrensel misina bağlama ve iki misinayı birbirine ekleme düğümü.', short_desc_en: 'Universal knot for line attachment.', content_tr: 'Uni Knot; hem iğne/klips bağlamada hem de iki misinayı birbirine birleştirmede kullanılan çok yönlü düğümdür.', content_en: 'Uni knot.', image_url: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', water_type: 'Tüm Sular', difficulty_level: 'Başlangıç', is_active: true },
  { category: 'knots', title_tr: 'Improved Clinch Knot', title_en: 'Improved Clinch Knot', short_desc_tr: 'Klips ve iğne deliklerine pratik misina bağlama düğümü.', short_desc_en: 'Classic terminal connection knot.', content_tr: 'Improved Clinch; klasik balıkçı düğümüdür, klips ve iğne deliklerine misina sabitlemede kullanılır.', content_en: 'Clinch knot.', image_url: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', water_type: 'Tüm Sular', difficulty_level: 'Başlangıç', is_active: true },
  { category: 'knots', title_tr: 'Rapala Knot (Non-Slip Loop)', title_en: 'Rapala Knot', short_desc_tr: 'Sahtelerin suda serbest zikzak yapmasını sağlayan klipsiz halka düğümü.', short_desc_en: 'Non-slip loop knot for lures.', content_tr: 'Rapala Knot; maket balığa klips takılmadan bağlandığında sahtenin suda bağımsız aksiyon yapmasını sağlayan halkalı düğümdür.', content_en: 'Rapala loop knot.', image_url: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80', water_type: 'Tüm Sular', difficulty_level: 'Orta', is_active: true },
  { category: 'knots', title_tr: 'Drop Shot Knot', title_en: 'Drop Shot Knot', short_desc_tr: 'Drop shot iğnesini misina üzerinde 90 derece dik tutan özel düğüm.', short_desc_en: 'Hook position knot for drop shotting.', content_tr: 'Drop Shot Knot; iğnenin misina üzerinde yukarı bakacak şekilde dik durmasını sağlayan özel finess düğümüdür.', content_en: 'Drop shot knot.', image_url: 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', water_type: 'Tüm Sular', difficulty_level: 'Başlangıç', is_active: true }
];

async function runSeed() {
  console.log('Inserting all articles into Supabase...');
  for (const art of ALL_ARTICLES) {
    await supabase.from('wiki_articles').delete().eq('title_tr', art.title_tr);
    const { error } = await supabase.from('wiki_articles').insert([art]);
    if (!error) console.log('Added:', art.title_tr);
  }
}
runSeed();
