-- =========================================================================
-- WIKI REHBERİ TÜM SİSTEMATİK VERİ PAKETİ (TAM KADRO)
-- =========================================================================

INSERT INTO public.wiki_articles (category, title_tr, title_en, short_desc_tr, short_desc_en, content_tr, content_en, image_url, water_type, difficulty_level, is_active) VALUES

-- -------------------------------------------------------------------------
-- 1. SAZAN RİGLERİ VE MONTAJLARI (Tam Kadro)
-- -------------------------------------------------------------------------
('rigs', 'Hair Rig', 'Hair Rig', 'Yemi iğneden bağımsız sunan en temel sazan rigi.', 'Classic carp hair rig presentation.', 'Hair Rig; yemin iğneye doğrudan takılmak yerine iğne altındaki kıl misinaya dizilerek balığın temkinsiz emmesini sağlayan temel sazan montajıdır.', 'Classic hair rig.', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Başlangıç', true),
('rigs', 'Ronnie Rig / Spinner Rig', 'Ronnie Rig', 'Pop-up yüzen yemlerde 360 derece dönebilen en popüler agresif sazan rigi.', '360 degree rotating pop-up rig.', 'Ronnie Rig; pop-up yemlerin dipteki otlardan 2-4 cm yukarıda askıda durmasını sağlayan ve iğneye 360 derece serbest dönüş vererek harika kanca tutuşu sunan rigdir.', 'Pop-up spinner rig.', 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Orta', true),
('rigs', 'Chod Rig', 'Chod Rig', 'Çamurlu ve otlu zeminlerde pop-up yemin otların üstünde temiz kalmasını sağlayan rig.', 'Silt and weed pop-up rig.', 'Chod Rig; kurşun çamura veya tortuya gömülse bile sert fluorocarbon yemin otların üzerinde tertemiz askıda kalmasını sağlar.', 'Chod rig for silt.', 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'İleri', true),
('rigs', 'Blowback Rig', 'Blowback Rig', 'Boilie yemin halka üzerinde serbest hareket etmesini sağlayan rig.', 'Free sliding ring rig.', 'Blowback Rig; sazan yemi dışarı üflemeye çalıştığında yemin halka üzerinde kayarak iğnenin ağızda takılı kalmasını sağlar.', 'Blowback rig.', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Orta', true),
('rigs', 'Snowman Rig', 'Snowman Rig', 'Batan boilie ve yüzen pop-up kombinasyonu nötr dengeli kardan adam rigi.', 'Neutral balanced snowman presentation.', 'Snowman Rig; batan boilie üzerine yüzen pop-up dizilerek yem nötr dengeli hale getirilir.', 'Snowman presentation.', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Başlangıç', true),
('rigs', 'Zig Rig', 'Zig Rig', 'Yazın orta suda ve yüzey altında askıda yüzen sazanları avlamak için uzun rig.', 'Mid-water and surface carp rig.', 'Zig Rig; sıcak havalarda dibe yatmayan sazanları orta su kolonunda (1-3 metre yukarıda) avlamak için sünger yemle hazırlanan uzun rigdir.', 'Midwater zig rig.', 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Orta', true),
('rigs', 'Method Hair Rig', 'Method Hair Rig', 'Method feeder yemlik etrafına sarılan hamur ortasında kısa 8-10cm hızlı kanca rigi.', 'Short feeder hair rig.', 'Method Feeder Rig; yemlik etrafındaki hamurun dağılmasıyla yemin tam merkezde balığa sunulmasını sağlar.', 'Method feeder rig.', 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Başlangıç', true),
('rigs', 'KD Rig', 'KD Rig', 'Temkinli balıklarda agresif kanca açısı sağlayan rig.', 'Aggressive hooking carp rig.', 'KD Rig; iğne gözünün hemen altından çıkan kıl sayesinde iğnenin uç kısmının ağır basarak alt dudağa hızlı saplanmasını sağlar.', 'KD rig.', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Orta', true),
('rigs', 'D Rig & Slip D Rig', 'D Rig', 'Pop-up ve wafter sunumunda doğal duruş ve kanca tutuşu sağlayan rig.', 'D loop presentation rig.', 'D Rig; D şeklinde oluşturulan halkanın üzerinde yemin kayarak kancanın batmasını kolaylaştırdığı mükemmel bir montajdır.', 'D-rig.', 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Orta', true),
('rigs', 'Combi Rig', 'Combi Rig', 'Sert ve yumuşak misinanın birleşimi ile takılmayı önleyen rig.', 'Combined stiff and soft braid rig.', 'Combi Rig; atışta dolaşmayı önleyen sert arka misina ile doğal haraketi sağlayan yumuşak ön misinayı birleştirir.', 'Combi rig.', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'İleri', true),

-- -------------------------------------------------------------------------
-- 2. BALIKÇILIK DÜĞÜMLERİ (Tam Kadro)
-- -------------------------------------------------------------------------
('knots', 'FG Knot (İp + Lider Düğümü)', 'FG Knot', 'İp misina ile Fluorocarbon lider birleştirmede sıfır pürüzlü en güçlü düğüm.', 'Slimmest braid to leader knot.', 'FG Knot; ip misinanın lider etrafına örülmesiyle atılan, porselen fincanlardan takılmadan geçen rakipsiz düğümdür.', 'FG knot.', 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'İleri', true),
('knots', 'Alberto Knot (Crazy Alberto)', 'Alberto Knot', 'İp ile lider misinayı sahada çok hızlı ve pratik birleştiren düğüm.', 'Fast braid to leader knot.', 'Alberto Knot; rüzgarlı havalarda ve geceleri hızlıca atılabilen yüksek çekergüçlü lider düğümüdür.', 'Alberto knot.', 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Orta', true),
('knots', 'Knotless Knot (Düğümsüz Düğüm)', 'Knotless Knot', 'Sazan balıkçılığında Hair Rig hazırlamak için kanca sapına sarılan düğüm.', 'Essential knot for carp hair rigs.', 'Knotless Knot; sazan iğne sapı etrafına 7-8 tur sarılarak Hair Rig oluşturan kolay ve güçlü düğümdür.', 'Knotless knot.', 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Başlangıç', true),
('knots', 'Palomar Knot', 'Palomar Knot', 'Klips, fırdöndü ve iğnelere misina bağlamada %95+ çeker güçlü en güvenilir düğüm.', 'Strongest knot for terminal tackle.', 'Palomar Knot; ip ve misinaların klipse ve fırdöndüye kaymadan baglanmasını sağlayan en sağlam düğümdür.', 'Palomar knot.', 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Başlangıç', true),
('knots', 'Uni Knot & Double Uni', 'Uni Knot', 'Evrensel misina bağlama ve iki misinayı birbirine ekleme düğümü.', 'Universal knot for line attachment.', 'Uni Knot; hem iğne/klips bağlamada hem de iki misinayı birbirine birleştirmede kullanılan çok yönlü düğümdür.', 'Uni knot.', 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Başlangıç', true),
('knots', 'Improved Clinch Knot', 'Improved Clinch Knot', 'Klips ve iğne deliklerine pratik misina bağlama düğümü.', 'Classic terminal connection knot.', 'Improved Clinch; klasik balıkçı düğümüdür, klips ve iğne deliklerine misina sabitlemede kullanılır.', 'Clinch knot.', 'https://images.unsplash.com/photo-1527838832700-5059252407fa?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Başlangıç', true),
('knots', 'Rapala Knot (Non-Slip Loop)', 'Rapala Knot', 'Sahtelerin suda serbest zikzak yapmasını sağlayan klipsiz halka düğümü.', 'Non-slip loop knot for lures.', 'Rapala Knot; maket balığa klips takılmadan bağlandığında sahtenin suda bağımsız aksiyon yapmasını sağlayan halkalı düğümdür.', 'Rapala loop knot.', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Orta', true),
('knots', 'Drop Shot Knot', 'Drop Shot Knot', 'Drop shot iğnesini misina üzerinde 90 derece dik tutan özel düğüm.', 'Hook position knot for drop shotting.', 'Drop Shot Knot; iğnenin misina üzerinde yukarı bakacak şekilde dik durmasını sağlayan özel finess düğümüdür.', 'Drop shot knot.', 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Başlangıç', true),

-- -------------------------------------------------------------------------
-- 3. SAHTE YEM ÇEŞİTLERİ (Tam Kadro)
-- -------------------------------------------------------------------------
('lures', 'Floating & Sinking Minnow', 'Minnow Lures', 'Yüzey ve orta suda yaralı balık aksiyonu veren gagalı maket sahteler.', 'Diving lip hard minnows.', 'Minnow sahteler; gaga yapıları sayesinde suda yaralı balık gibi yalpalayarak yırtıcıları cezbeder.', 'Minnow lure.', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Orta', true),
('lures', 'Popper & WTD Stickbait', 'Topwater Lures', 'Su yüzeyinde şapırtı ve WTD zikzağı ile avcı balıkları uyaran sahteler.', 'Topwater splashers and walkers.', 'Su üstü sahteleri; su yüzeyinde kırılma, ses ve köpük çıkararak yırtıcı balıkları uyarır.', 'Topwater lure.', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Orta', true),
('lures', 'Jighead & Silikon Yemler (Shad, Worm, Craw)', 'Soft Plastic Lures', 'Balık, solucan ve karides silikonlarının jigheadli modelleri.', 'Soft plastic lures with jigheads.', 'Yumuşak silikon yemler, aksiyonel yapıları ve kokulu modelleriyle LRF ve Spin avcılığının vazgeçilmezidir.', 'Soft plastics.', 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Başlangıç', true),
('lures', 'Metal Kaşıklar & Shore Jigler', 'Spoons & Metal Jigs', 'Uzak atış parıltılı kaşıklar ve asist iğneli jigler.', 'Casting spoons and assist hook jigs.', 'Ağır yapısıyla uzak mesafelere ulaşan parıltılı metal kaşıklar ve shore jigler.', 'Metal lures.', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Başlangıç', true),
('lures', 'EGI Kalamar & Sübye Zokası', 'EGI Squid Lure', 'Kumaş kaplı şemsiye tırnaklı gece kalamar zokası.', 'Squid and cuttlefish EGI lures.', 'EGI zokaları kumaş kaplı gövdesi ve şemsiye iğneleriyle kalamar ve sübye avcılığında kullanılır.', 'Squid EGI lure.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'Tuzlu Su', 'Başlangıç', true),
('lures', 'Metal Vibrasyon & Blade Vibe', 'Metal Vibration Lure', 'Yüksek frekansta titreyerek yırtıcıları çeken metal sahteler.', 'High vibration metal blade lures.', 'Metal vibrasyon sahteleri hızlı sarımda yoğun titreşim yayarak balıkların yan çizgi organlarını uyarır.', 'Vibration blade.', 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Orta', true),

-- -------------------------------------------------------------------------
-- 4. KAMIŞ VE MAKİNE ÇEŞİTLERİ (Türkçe İsimler & Tam Kadro)
-- -------------------------------------------------------------------------
('tackles', 'Spin Makinesi (Spinning Reel)', 'Spinning Reel', 'At-çek balıkçılığı için ön kalamalı standart olta makinesi.', 'Standard front drag lure casting reel.', 'Spin makineleri hafifliği ve yüksek sarım kalitesi ile en yaygın kullanılan at-çek makinesidir.', 'Spinning reel.', 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Başlangıç', true),
('tackles', 'Surfcast (Big Pit) Makine', 'Surf Big Pit Reel', 'Geniş konik makaralı 100m+ uzağa atış ve Boğaz makinesi.', 'Long cast tapered spool surf reel.', 'Surf makineleri konik makara yapısıyla ipin rahat boşalmasını sağlayarak maksimum atış mesafesi sunar.', 'Big pit reel.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'Tuzlu Su', 'Orta', true),
('tackles', 'Sazan Makinesi (Baitrunner / Serbest Makara)', 'Carp Baitrunner Reel', 'Çift kalamalı, balık kaçarken misinayı boşa salan sazan makinesi.', 'Dual drag freespool carp reel.', 'Baitrunner makineler balık yemi aldığında misinayı sıfır dirençle boşa salar, kol çevrilince kalama devreye girer.', 'Baitrunner reel.', 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Başlangıç', true),
('tackles', 'Baitcasting & Çıkrık Makine', 'Baitcasting Reel', 'Tetikli kamışlarla kullanılan torklu yüksek hassasiyetli makine.', 'Overhead revolving spool reel.', 'Tetikli kamışların üzerinde duran ve başparmak kontrolüyle atış yapılan güçlü makinedir.', 'Baitcasting reel.', 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'İleri', true),
('tackles', 'Spin Kamışı', 'Spinning Rod', '2.40m - 2.70m uzunluğunda esnek iki parçalı at-çek kamışı.', 'Standard 2-piece lure casting rod.', 'Spin kamışları 7-35g atar aralıklarıyla sahtelere aksiyon vermeyi sağlayan hafif kamışlardır.', 'Spinning rod.', 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Başlangıç', true),
('tackles', 'LRF Kamışı', 'LRF Rod', '2.10m - 2.30m 0.5-10g atarlı hassas uçlu ultra hafif kamış.', 'Ultra-light sensitive tip rod.', 'LRF kamışları mikro yemlerin en ufak vuruşunu bile kamış sapına ileten hassas kamışlardır.', 'LRF rod.', 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=800&q=80', 'Tüm Sular', 'Başlangıç', true),
('tackles', 'Surfcast Kamışı', 'Surfcasting Rod', '4.20m - 4.50m 100-250g atarlı güçlü kıyı kamışı.', 'Heavy duty beach casting surf rod.', 'Surf kamışları dalgalı kıyılardan ağır kurşunları uzağa fırlatmak için tasarlanmıştır.', 'Surf rod.', 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80', 'Tuzlu Su', 'Orta', true),
('tackles', 'Sazan Kamışı (Carp Rod)', 'Carp Rod', '3.60m - 3.90m 3.0-3.5 lb test eğrili esnek sazan kamışı.', '12-13ft test curve carp fishing rod.', 'Sazan kamışları uzun yapısı ve esnek parabolik aksiyonu ile trofe sazanları yormaya yarar.', 'Carp rod.', 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?auto=format&fit=crop&w=800&q=80', 'Tatlı Su', 'Orta', true);
